### ISSUE TITLE
Snake Visual Bug

### ISSUE THREAD

**Issue by not-matthias** [htl-perg-2018-19-4ahif/snake-exercise-not-matthias#1]
# Overview
## Description
This bug just renders another point one field ahead the actual position. I tried debugging it, but I couldn't find anything useful. The movement is working fine. The removal of the snake is working fine too and the bug is still there even if I remove the snake removal function.

## Images
The yellow point is the right position. (3 | 2). The gray point is the one, which I don't know where it comes from. I tried stepping through the code with the debugger, but there wasn't any strange stuff. Everything working as expected...
![image](https://user-images.githubusercontent.com/26800596/46174564-aba85f00-c2a9-11e8-93f7-7b77a048eb82.png)

EDIT: The current version is extra slow, in order to make it easier to debug it (in the debug branch). The point should be drawn at ( 3 | 2) the first time.

**Comment by rstropek** [comment]
Will take a look as soon as possible

**Comment by not-matthias** [comment]
Hiding the cursor fixed the issue. Thanks for helping. 👍
