### ISSUE TITLE
Replace start_snake.bat with script in package.json

### ISSUE THREAD

**Issue by rstropek** [htl-perg-2018-19-4ahif/snake-exercise-not-matthias#2]
Hi @not-matthias!

You have a helper script *start_snake.bat* to start your app. Consider replacing it with a `script` in *package.json*. Read more in the [NPM docs](https://docs.npmjs.com/misc/scripts), in particular [here](https://docs.npmjs.com/misc/scripts#default-values).

Greetings,
Rainer Stropek.

**Comment by not-matthias** [comment]
Already had a script in the package.json, but didn't to remove the script.
